apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01-kind-worker
  labels:
    name: pv01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: standard
  local:
    path: /some/path/in/container
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02-kind-worker2
  labels:
    name: pv02
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: standard
  local:
    path: /some/path/in/container
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      name: pv01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-deployment
  labels:
    app: playwright-run
spec:
  selector:
    matchLabels:
      app: playwright-run
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: playwright-run
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc01
      containers:
      - name: playwright-container
        image: virgiliusmaximus/vrepo:v2
        command: ["/bin/sh", "-c", "chmod 777 /playwright/install_playwright.sh && cd /playwright && ./install_playwright.sh && sleep 360000"]
        volumeMounts:
          - name: storage
            mountPath: /playwright
        ports:
        - name: http
          containerPort: 80
        env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
---
apiVersion: v1
kind: Service
metadata:
  name: kind-loadbalancer
spec:
  selector:
    app: playwright-run
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
